source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Aerodramus_Example', :exclusive => true do
  pod "Aerodramus", :path => "../"
end

target 'Aerodramus_Tests', :exclusive => true do
  pod "Aerodramus", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
