use_frameworks!
platform :ios, '8.0'

if ENV["CI"]
    `bundle exec pod keys set EchoKey -`
end

plugin 'cocoapods-keys', {
    :project => "Aerodramus",
    :target => "Aerodramus_Example",
    :keys => ["EchoKey"]
}

target 'Aerodramus_Example' do
  pod "Aerodramus", :path => "../"

  target 'Aerodramus_ExampleTests' do
    inherit! :search_paths
    
    pod 'Specta'
    pod 'Expecta'
    pod 'Forgeries'
  end
end
