use_frameworks!
platform :ios, '8.0'

target 'Aerodramus_Example' do
  pod "Aerodramus", :path => "../"

  target 'Aerodramus_ExampleTests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'Forgeries'
  end
end
